# Middleware pour redirection HTTPS
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: certs
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
# API
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-route
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  entryPoints:
    - websecure
  tls:
    secretName: tls-secret
  routes:
  - match: Host(`api.okloud-hub.com`)
    kind: Rule
    services:
    - name: music-server
      port: 10000

---
apiVersion: traefik.containo.us/v1alpha1  # Notez le changement de traefik.io à traefik.containo.us
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.okloud-hub.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.okloud-hub.com`) && Headers(`Content-Type`, `application/grpc`)  # Notez 'Headers' au lieu de 'Header'
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: tls-secret
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true"

---

# ingress-routes.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: music-frontend
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`music.okloud-hub.com`)
      kind: Rule
      services:
        - name: music-frontend
          port: 80
  tls:
    secretName: tls-secret