# Middleware pour redirection HTTPS
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: certs
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-music-api
  namespace: apps
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    accessControlAllowHeaders:
      - "Authorization"
      - "Content-Type"
      - "Accept"
      - "Origin"
      - "User-Agent"
    accessControlAllowOriginList:
      - "https://music.okloud-hub.com"
    accessControlAllowCredentials: true
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-route
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.okloud-hub.com`)
      kind: Rule
      middlewares:
        - name: cors-music-api
          namespace: apps
      services:
        - name: music-server
          port: 10000
  tls:
    secretName: tls-secret

---
apiVersion: traefik.containo.us/v1alpha1  # Notez le changement de traefik.io à traefik.containo.us
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.okloud-hub.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.okloud-hub.com`) && Headers(`Content-Type`, `application/grpc`)  # Notez 'Headers' au lieu de 'Header'
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: tls-secret
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true"
  url: http://192.168.1.97

---

# ingress-routes.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: music-frontend
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`music.okloud-hub.com`)
      kind: Rule
      services:
        - name: music-frontend
          port: 80
  tls:
    secretName: tls-secret