apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-server
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-server
  template:
    metadata:
      labels:
        app: music-server
    spec:
      containers:
      - name: api
        image: ousmanekk/music-api:latest
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          value: "music_share"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: music-server
  namespace: apps
spec:
  ports:
  - port: 80
  selector:
    app: music-server