apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-role
  namespace: apps
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-role-binding
  namespace: apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-role
subjects:
- kind: ServiceAccount
  name: postgres-sa
  namespace: apps
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apps
type: Opaque
data:
  # La valeur doit être en base64
  POSTGRES_PASSWORD: RHJvZ29iZWF0czE5OTUq