# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
#   namespace: apps
# spec:
#   storageClassName: longhorn  # On utilise Longhorn qu'on a déjà configuré
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi